[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/',
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
]


[fuzz]
runs = 500


[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[profile.rpc]
gas_limit = 30000000

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
